server:
  port: 8081
  servlet:
    context-path: /ribbon
#  Eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
spring:
  application:
    name: ribbon-service